### ISSUE TITLE
can I translate the game using this?

### ISSUE THREAD

**Issue by kroamele1232** [Kaplas80/GuJian3Manager#2]
how can I?

**Comment by Kaplas80** [comment]
No, sorry, I haven't found the texts inside the game.

**Comment by kroamele1232** [comment]
> No, sorry, I haven't found the texts inside the game.

Could it be inside .exe?

**Comment by Kaplas80** [comment]
Yes, I think they are encrypted inside the .exe file

**Comment by kroamele1232** [comment]
:( sad thanks for reply
