### ISSUE TITLE
.xxx file key

### ISSUE THREAD

**Issue by barnett2010** [Kaplas80/GuJian3Manager#21]
Where can I find the key of this .xxx file,
Is there a link

**Comment by barnett2010** [comment]
cutscene\1010\cs_1010_1a.xxx: 84bf71f9a6a44fa3f3e1a266166dac7297f6018b
cutscene\1010\cs_1010_1b.xxx: 3cdfdf73bef25ae40a40215025fcabaffca2c72a
interface\resource\movie\cg00100b.xxx: 25bcfb70b5cc7e0f2253ffe8a9e3d6e831aad2f5
interface\resource_en\movie\optxt.xxx: 73be7f337c0c248926630719cdbe927895866a41
maps\m01\elems.xxx: 4a40a9712bfdc8e79c46b0ab735130d947dfe6f1
sounds_console\bgm.xxx: 5ff3f69e1d15a67f5d578dbc4d7ce263c1e83135
sounds_console\bgm_p1.xxx: b388c0bf15d0b39c684a0af3c2c3b925c00598b0
sounds_console\voice.xxx: 7ba2771ca1907e9f7348f38a5b8b3881d44db8a2
sounds_console\voice_npc.xxx: 960513d4e71a2b003eda159891e102c43e344eed
sounds_console\voice_p1.xxx: 1b2466ac36ee2e9c2fce01f76dbb1e873df42c06

**Comment by barnett2010** [comment]
gujian3tool decrypt voice_p1.xxx voice_p1.fsb --key 1b2466ac36ee2e9c2fce01f76dbb1e873df42c06
GuJian3Tool 1.1.1+eebf338bbc4c64f330e02d7313888bb3c0a8a0c1
Copyright (C) 2021 Kaplas

Decrypting...
 DONE!

**Comment by barnett2010** [comment]
new file  voice_p1.fsb Not a normal bank file
Cannot unpack ogg

**Comment by Kaplas80** [comment]
Those are old keys, used in the previous version of the app. The new keys are [here](https://github.com/Kaplas80/GuJian3Manager/blob/eebf338bbc4c64f330e02d7313888bb3c0a8a0c1/src/GuJian3Tool/Program.cs#L36)

Anyway, if you use the full path for the files, you don't need to write the key, as the app gets it automatically:

```
GuJian3Tool.exe decrypt "C:\Gujian3\extracted-data\asset\sounds_console\voice_p1.xxx" "C:\Gujian3\decrypted-data\voice_p1.fsb"
```

Replace `C:\Gujian3\extracted-data` and `C:\Gujian3\decrypted-data` with your input and output folders and it should work.

**Comment by barnett2010** [comment]
@Kaplas80  thank you

**Comment by barnett2010** [comment]
I'll try it now. 
My game version is  
gujian3.exe version 1.3.0.2142

**Comment by barnett2010** [comment]
GuJian3Tool.exe extract-single "E:\GU3\data\data030" "E:\gu3jpjb" --index "E:\GU3\data\_index\303.idx"

WARNING: Output directory already exists. Its contents may be overwritten.
Continue? (y/N) y
Loading index file... DONE!
Loading 'E:\GU3\data\data030' (this may take a while)... DONE!

I want to export this file data30
Then use the above command,
No files exported,
 a new file is generated in the original directory
data30.test

**Comment by Kaplas80** [comment]
You are right, the `extract-single` command is not working. I'll try to fix it as soon as possible.

**Comment by barnett2010** [comment]
There's a temporary way,
 remove other data files 
and leave only one data030 file.

**Comment by barnett2010** [comment]
I re extracted the XXX file from data030
It was found that the xxx file extracted by steam and wangyuan was different.
After decrypting the file with Steam, 
the file header 
finally has the characteristics of a bank file.
