### ISSUE TITLE
Please advise

### ISSUE THREAD

**Issue by stbz4088** [Kaplas80/GuJian3Manager#24]
Hi, I presented your tool in the video, if you think I shouldn't do this without consent, please contact me by email. Here is my email and the link to the video.
lzy4088@gmail.com
https://www.bilibili.com/video/BV1bF41137Xw

**Comment by Kaplas80** [comment]
Hi. No problem with that.

Thank you!

**Comment by stbz4088** [comment]
Hi,I'm here again and I'd like to ask a few questions.

**Comment by stbz4088** [comment]
Hi,I'm here again and I'd like to ask a few questions.
I used your tool last year to successfully replace the character outfits, but I want to keep the original outfits and add some new ones instead of replacing them.If I could achieve the additional effect, I would be able to switch between outfits at any time in the game as I did before, instead of giving up the outfits that are already in the game. I don't know how to do this, can you guide me please, thank you very much. (I don't know anything about game development)

**Comment by Kaplas80** [comment]
Hello,

I'm sorry, but I don't know how to do what you want. It would need a deep understanding about the game internal functions that I don't have.

**Comment by stbz4088** [comment]
It's OK. What a shame it is

**Comment by stbz4088** [comment]
> Hello,
> 
> I'm sorry, but I don't know how to do what you want. It would need a deep understanding about the game internal functions that I don't have.


It's OK. What a shame it is
