### ISSUE TITLE
ERROR: "oo2core_6_win64.dll" not found!!!!

### ISSUE THREAD

**Issue by butterSohaa** [Kaplas80/GuJian3Manager#25]
PS C:\Users\Administrator\source\repos> E:\serect\code\GuJian3Tool_win-x64_v1.1.2\GuJian3Tool.exe build E:\serect\asset E:\serect\古剑奇谭三\data\_index\300.idx
GuJian3Tool 1.1.2+fead1909671b045bbdf18977eff90436dfacc7cc
Copyright (C) 2021 Kaplas
ERROR: "oo2core_6_win64.dll" not found!!!!

I tried to Add / Replace files in data files but failed.
the errorr displayed in the powershell——"oo2core_6_win64.dll not found!!!!" 
however,I have already put the oo2core_6_win64 under the gujian3managertool before run the command...

Can you help me solve this problem？thanks very much！！

**Comment by butterSohaa** [comment]
我的英语不是很好……TvT，希望能大致表达清楚。

**Comment by butterSohaa** [comment]
我的英语不是很好……TvT，希望能大致表达清楚。

**Comment by butterSohaa** [comment]
I didn't use the Steam,…so it displayed 300.idx instead of 303.idx.🧐

**Comment by butterSohaa** [comment]
I didn't use the Steam,…so it displayed 300.idx instead of 303.idx.🧐

**Comment by butterSohaa** [comment]
To be honest，I just want to know this dll where I should copy it？？

**Comment by butterSohaa** [comment]
It is very very very important for
me!!!!🥺
but I don't know what should I do…

**Comment by Kaplas80** [comment]
Hello!

`oo2core_6_win64.dll` has to be located in the same directory than `GuJian3Tool.exe`. I've just published v1.1.3 that solves this bug. 

Please, let me know if it works.

PS. Please, next time do not spam in the issues, it is enough with just one message. I read the issues and try to fix them when I have time.

**Comment by butterSohaa** [comment]
Thanks your work!it can work successfully!!🥰
Besides,I'm sorry to send you spam………
