### ISSUE TITLE
Any instruction on how to build Gujian3Tool.exe?

### ISSUE THREAD

**Issue by plr0201** [Kaplas80/GuJian3Manager#27]
**Is your feature request related to a problem? Please describe.**

->Probably yes. For one with little programming background, it is very difficult to figure out how to use the tool. In other words, where is the "Gujian3Tool.exe"? Need to build?

**Describe the solution you'd like**

-> Is it possible to at least instruct which tools should be use for the building? Does it work on win10? or has to be in linux? Would be grateful if a brief instruction could be provided.

**Describe alternatives you've considered**

->Attach a "Gujian3Tool.exe" into the github folder. More favorable probably.

**Additional context**

->Thank you very much for the tool!

**Comment by plr0201** [comment]
Find the solution. Although extract-single doesn't work, the extract all works great. Thanks!

**Comment by plr0201** [comment]
Install microsoft net ver 6 SDK for the dotnet command to build the app.

**Comment by Kaplas80** [comment]
I'm glad to hear that you found a way to build the application. Anyway, you had the precompiled executables for Windows, Mac and Linux at the "Releases" section of the page:

![image](https://user-images.githubusercontent.com/5345429/168464282-7ad55740-c9e5-484a-88fb-592a5149f58d.png)

About the `extract-single` option, last time I checked, it worked. Could you tell me what error you get?

**Comment by plr0201** [comment]
No error message shown. Just, empty folder.

**Comment by plr0201** [comment]
> I'm glad to hear that you found a way to build the application. Anyway, you had the precompiled executables for Windows, Mac and Linux at the "Releases" section of the page:
> 
> ![image](https://user-images.githubusercontent.com/5345429/168464282-7ad55740-c9e5-484a-88fb-592a5149f58d.png)
> 
> About the `extract-single` option, last time I checked, it worked. Could you tell me what error you get?

Thank you for response! No error msg shown, just empty folder. You made a great app!
