### ISSUE TITLE
Adding Tutorials for Mac/Linux Builds

### ISSUE THREAD

**Issue by GuardHei** [Kaplas80/GuJian3Manager#28]
**Is your feature request related to a problem? Please describe.**
I'm trying to get this tool working on MacOS using the precompiled version package provided. However, I have no idea on how to run the tool. There's the .exe file on Windows, which is not the case on mac. I'm not sure which command to call from MacOS's terminal (bash or zsh). I've tried "GuJian3Tool info some_path_to_303.idx", but I don't think the command is recognized.
Also, since the tool requires "oo2core_6_win64.dll", will it even run on mac? (I have copied the lib to the tool folder) 

**Describe the solution you'd like**
Add a section in README to illustrate how to use the tool on mac or linux.

**Describe alternatives you've considered**
NA

**Additional context**
Nice tool!

**Comment by Kaplas80** [comment]
Hello!

These are the steps to run in linux (I don't have a mac, but I think they are the same):

1. Download and extract the files
2. Open a terminal and `cd` to the directory
3. Set permissions to read and write the files in the directory: `chmod 644 *`
4. Set permission to run the executable file: `chmod +x GuJian3Tool`
5. Run the application: `./GuJian3Tool`

![image](https://user-images.githubusercontent.com/5345429/188082307-fa94c7ab-0f63-46e5-90ee-ce58452d74d7.png)

About the second question, `oo2core_6_win64.dll` is used to extract and repack data files, so those commands won't work in linux/macos. But the other options work well.

**Comment by GuardHei** [comment]
I see. So if I want to extract the map models, I have to use Win anyway?
