### ISSUE TITLE
有没有成品exe

### ISSUE THREAD

**Issue by barnett2010** [Kaplas80/GuJian3Manager#3]
打包一直报错

**Comment by Kaplas80** [comment]
Please, write in English.

**Comment by barnett2010** [comment]
OK. Thanks for your reply
I would like to ask, is there a compiled exe file to download?
I keep getting errors when I compile. Prompted by missing files, the error message has more than a thousand.

--------------
I have tried to restore the xxx file to a bank file.
then use fsb_aud_extr to export ogg

**Comment by Kaplas80** [comment]
Hello!

I'm sorry, but there isn't a compiled exe. But I've just tried to compile using [git](https://git-scm.com/downloads) and [dotnet SDK](https://dotnet.microsoft.com/download/dotnet/5.0) and it works fine:

```shell
git clone --recurse-submodules https://github.com/Kaplas80/GuJian3Manager.git

cd GuJian3Manager/src

dotnet build
```

Also, Visual Studio 2019 compiles it correctly.
