### ISSUE TITLE
Could not encrypt files

### ISSUE THREAD

**Issue by alanm20** [Kaplas80/GuJian3Manager#30]
-Downloaded latest  version v1.1.3. I can decrypt single xxx file but  I cannot encrypt it back for some reason.

-GuJian3Tool.exe decrypt "..\data\output\asset\cutscene\1040\CS_1040_2E.xxx" cs1040_2e.txt

return a decrypted cs1040_2e.txt file.  

-Tried to encrypt it back with "GuJian3Tool.exe encrypt cs1040_2e.txt  output.xxx"

GuJian3Tool 1.1.3+4ee8106523e56962020b02e4f73b27496ff98147
Copyright (C) 2021 Kaplas

ERROR: Encryption key not found!!

-Tool complaint Encryption key not found. key suppose to be optional?

Any help is appreciated

**Comment by Kaplas80** [comment]
To allow the program to automatically find the encryption key it has to use, the input file you pass it has to be in the same relative path and named the same as the original encrypted file. In your case, it could be something like this:

`GuJian3Tool.exe encrypt ..\modified\data\output\asset\cutscene\1040\CS_1040_2E.xxx output.xxx`

Both, the directory where the file is located, the capital letters and the `xxx` extension are important.

In other case, you should have to search the encryption key in [this list](https://github.com/Kaplas80/GuJian3Manager/blob/4ee8106523e56962020b02e4f73b27496ff98147/src/GuJian3Tool/Program.cs#L36) and pass it as parameter:

`GuJian3Tool.exe encrypt cs1040_2e.txt output.xxx --key 146machg80aae9aa`

**Comment by alanm20** [comment]
Got it. Your instructions solve my issue.  Thank you for your help.
